annotation_file: 
batch_size: 8
img_dir: 
num_classes: 5
random_state: 2022
split_dataset: true
checkpoint_cfg:
  load_path:
  save_path:
  eval_metric: loss
  eval_criterion: less
  save_each_epoch: null
trainer:
  deterministic: true
  gpus: 0
  wandb_logger:
    project: simple_img_classify_engine
