wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.8.10
    start_time: 1653315800
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      3:
      - 7
      - 23
      4: 3.8.10
      5: 0.12.16
      8:
      - 1
      - 5
num_classes:
  desc: null
  value: 5
