dataloader:
  annotation_file: "/home/vanchez/Data/ArtLabs/all_flowers/annotation_file.csv"
  batch_size: 8
  img_dir: "/home/vanchez/Data/ArtLabs/all_flowers/images"
  num_classes: 5
  random_state: 2022
  split_dataset: true
checkpoint_cfg:
  load_path:
  experiment_path: "/home/vanchez/Data/ArtLabs/experiments"
  experiment_name: ""
  eval_metric: loss
  eval_criterion: less
  save_each_epoch: null
trainer:
  max_epochs: 3
  deterministic: true
  gpus: 0
  accelerator: gpu
  auto_select_gpus: true
  wandb_logger:
    project: simple_img_classify_engine
