wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    m:
    - 1: trainer/global_step
      6:
      - 3
    python_version: 3.8.10
    start_time: 1653318340
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      3:
      - 7
      - 23
      4: 3.8.10
      5: 0.12.16
      8:
      - 1
      - 5
cfg/annotation_file:
  desc: null
  value: /home/vanchez/Data/ArtLabs/all_flowers/annotation_file.csv
cfg/batch_size:
  desc: null
  value: 8
cfg/img_dir:
  desc: null
  value: /home/vanchez/Data/ArtLabs/all_flowers/images
cfg/num_classes:
  desc: null
  value: 5
cfg/random_state:
  desc: null
  value: 2022
cfg/split_dataset:
  desc: null
  value: true
cfg/trainer/deterministic:
  desc: null
  value: true
cfg/trainer/gpus:
  desc: null
  value: 0
cfg/trainer/wandb_logger/project:
  desc: null
  value: simple_img_classify_engine
